@startsalt
{+
{
{/ <b><&command> Действие | <&person> Анкета | <&cart> Корзина | Досье  }
{
{ VIN | "123459789      "
Тип проверки: | ^Расширенная^ }
[X] Проверка ГИБДД
[ ] Проверка Росреестр
}
[Завершить]
}

--
{
{/ <&command> Действие | <b><&person> Анкета | <&cart> Корзина | Досье  }
{
 <color:Blue>iframe src="https:///service1/questionnaire?uid=...."
{ ФИО | "Иванов Иван Петрович"
Дата рождения | "01.01.1970" }
}
}


--
{
{/ <&command> Действие | <&person> Анкета | <b><&cart> Корзина | Досье  }
{
 <color:Blue>iframe src="https:///service2/productcart?uid=...."
Автомобиль Lada Kalina 2007 г.в. 300 000 р.
Поручительство "Брокер" ООО 50 000 р.
Коробка "Найдется все" ООО 7 200 р.}
}


--
{
{/ <&command> Действие | <&person> Анкета | <&cart> Корзина | <b>Досье  }
{
 <color:Blue>iframe src="https:///service3/dossier?uid=...."

Загрузить { "file.pdf " | [Обзор...] }
(X) __Анкета__
() __Договор залога__
() Договор поручительства
() Кредитный договор
}
}


}




@endsalt
