@startuml
(*) --> "
{{
salt
{+
{
{/ <b><&command> Действие | <&person> Анкета | <&cart> Корзина | Досье  }
{
{ VIN | "123459789      "
Тип проверки: | ^Расширенная^ }
[X] Проверка ГИБДД
[ ] Проверка Росреестр
}
[Завершить]
}
}

}}
" as action

note right
    Основной экран сервиса,
    где пользователь выполняет работу
end note

action -down-> "
{{
salt
{
{/ <&command> Действие | <b><&person> Анкета | <&cart> Корзина | Досье  }
{
 <color:Blue>iframe src="https:///service1/questionnaire?uid=...."
{ ФИО | "Иванов Иван Петрович"
Дата рождения | "01.01.1970" }
}
}
}}
" as questionnaire

note right
    Для выполнения работы
    может понадобиться анкета клиента
    Подключим ее как iframe. Таким образом
    мы не зависим от предметной области анкеты
    Ссылка может быть подана в контексте вызова
    <color blue>link ref="questionnaire" href="https:///service1/questionnaire?uid=...."</color>
end note


questionnaire -down-> "
{{
salt
{
{/ <&command> Действие | <&person> Анкета | <b><&cart> Корзина | Досье  }
{
 <color:Blue>iframe src="https:///service2/productcart?uid=...."
Автомобиль Lada Kalina 2007 г.в. 300 000 р.
Поручительство "Брокер" ООО 50 000 р.
Коробка "Найдется все" ООО 7 200 р.}
}
}}
" as productcart

note right
    Для выполнения работы
    может понадобиться подобранная корзина
    Отобразим ее в iframe
end note

productcart -down-> "
{{
salt
{
{/ <&command> Действие | <&person> Анкета | <&cart> Корзина | <b>Досье  }
{
 <color:Blue>iframe src="https:///service3/dossier?uid=...."

Загрузить { "file.pdf " | [Обзор...] }
(X) __Анкета__
() __Договор залога__
() Договор поручительства
() Кредитный договор
}
}
}}
" as dossier

note right
    Для выполнения работы
    может понадобиться досье
    Отобразим его в iframe
end note

@enduml
